apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: service-tracker
spec:
  releaseName: nginx-ingress
  targetNamespace: service-tracker
  timeout: 300
  resetValues: false
  wait: false
  forceUpgrade: false
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 4.0.1
  values:
    controller:
      replicaCount: 2
      

